### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dongchenmiao** [lllllllllllll-llll/DIQA#1]
请问在iqadataset.py里的第27和29行有什么具体意义嘛。。。我知道做了什么，但是感觉没什么用啊

**Comment by lllllllllllll-llll** [comment]
Hello! The first step for DIQA is to pre-process the images. The image is converted into grayscale, and then a low-pass filter is applied.  The low-frequency image is the result of the following algorithm:
1. Blur the grayscale image; 
2. Downscale it by a factor of 1/4;
3. Upscale it back to the original size.
I believe you mean the progress of downscaling and upscaling.
