### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by dongchenmiao** [lllllllllllll-llll/DIQA#2]
When I run train_ step1.py, it said, "typeerror: can't convert CUDA tenant to numpy. Use Tensor.cpu () to copy the tensor to host memory first.”
Can you tell me the version of torch package? I think the problem may be the package version.
thank u.

**Comment by yinglili666** [comment]
> When I run train_ step1.py, it said, "typeerror: can't convert CUDA tenant to numpy. Use Tensor.cpu () to copy the tensor to host memory first.”
> Can you tell me the version of torch package? I think the problem may be the package version.
> thank u.

Hi, I have the same problem as you. How did you solve it?
